### ISSUE TITLE
Create the menu window

### ISSUE THREAD

**Issue by jazellemaira** [jazellemaira/jazellemaira.design#26]
Currently, there is no menu window.  Make the menu window and add the corresponding paths.

**Comment by ritik2358** [comment]
Hey @jazellemaira , Could you please assign me this issue.
I want to work on this.

**Comment by jazellemaira** [comment]
Hi @ritik2358, this repo is not open for contributions right now. Thanks anyway!

**Comment by ritik2358** [comment]
okay,
tell me if u want any contribution in this.
I'll contribute
